### PR TITLE
DPS: add GUIDs for missing Debian architectures

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by poettering** [comment]
x32 is not a cpu architecture, but just a different userspace abi for x86-64. I am not convinced it should be treated as architecture here. We don't have different ids for the myriad of arm abis here either.

**Comment by poettering** [comment]
(the other ones i am fine with)

**Comment by keszybz** [comment]
Let's have the discussion in the systemd PR and follow here with the decision made there.

**Comment by keszybz** [comment]
I closed the systemd PR, so I'll all close this one. It seems we need a different approach. The discussion is continuing.

**Pull request closed without merging**
