### PR TITLE
specs/: fix local cross-references

### PR DESCRIPTION
**Pull request by t-lo**
Document cross-references do not work on the website if a `.md` file is referenced.

### CODE REVIEW

**Review by brauner — APPROVED** [review]

**Comment by bluca** [comment]
This breaks following links on the github markdown visualizer, try to click on a link from https://github.com/uapi-group/specifications/blob/9580e78eb0bdf5232fa57b41be4d62265920c452/specs/discoverable_disk_image.md

**Comment by t-lo** [comment]
> This breaks following links on the github markdown visualizer, try to click on a link from https://github.com/uapi-group/specifications/blob/9580e78eb0bdf5232fa57b41be4d62265920c452/specs/discoverable_disk_image.md

That's correct, the links are currently written for processing with Hugo. We'll need to find a way to make it work with both website and Github markdown in the future; I don't think we're the only ones running into this issue.

**Comment by bluca** [comment]
The most important thing is that they work in github, as that's the most common way of reading things, so if there's no way to make them work in both, leave it broken in the website for now

**Comment by t-lo** [comment]
@bluca I found a better way to make the links work, should now work for both rendered website and github.

**Review by bluca — APPROVED** [review]

**Pull request merged**
