### PR TITLE
specs: relicense from LGPL-2.1-or-later to CC-BY-4.0

### LINKED ISSUE #6: change license?
In the systemd repo, we used `LGPL-2.1-or-later` because that's how the code is licensed. But it's a code license, not a text license. Maybe we should switch to something like ~~CC-BY-SA~~ CC-BY ?

### PR DESCRIPTION
**Pull request by bluca**
Fixes #6

### CODE REVIEW

**Comment by bluca** [comment]
Hello contributors, we'd like to relicense the discoverable partitions and bootloader specs, to which you contributed, from LGPL-2.1-or-later to CC-BY-4.0 to facilitate sharing. Please leave a comment if you agree with the change. Thank you!

@alyssais
@bnf
@keszybz
@nl6720
@poettering
@thesamesam
@tretter
@wbolster
@WhyNotHugo
@xen0n
@xnox
@yuwata

**Comment by bnf** [comment]
I agree.

**Comment by WhyNotHugo** [comment]
I have no objections, fine by me.

**Comment by xen0n** [comment]
Fine by me, thanks for the heads-up!

**Comment by nl6720** [comment]
👍

**Comment by yuwata** [comment]
I agree.

**Comment by wbolster** [comment]
✅ relicensing from LGPL-2.1-or-later to CC-BY-4.0 fine by me

**Comment by poettering** [comment]
Ok by me

**Comment by thesamesam** [comment]
Fine with me, thanks!

**Comment by tretter** [comment]
Fine by me.

**Comment by keszybz** [comment]
FTR, fine by me.

**Review by wbolster — APPROVED** [review]

**Comment by bluca** [comment]
Gentle ping @xnox @alyssais

**Comment by alyssais** [comment]
Agreed :)

**Comment by bluca** [comment]
Another ping @xnox

**Comment by xnox** [comment]
I agree with the relicensing @bluca

**Review by brauner — APPROVED** [review]

**Pull request merged**
